### ISSUE TITLE
[PE-D][Tester C] When _ key is input it is replaced with a space key instead

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W10-3/tp#244]
![image.png](https://raw.githubusercontent.com/Paulifyer/ped/main/files/d16d204f-667e-4736-9ce2-504e0b84fa76.png)
This may cause unintended problems for users

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Paulifyer/ped#4

**Comment by TVageesan** [comment]
Duplicate issue: #257
