### ISSUE TITLE
[PE-D][Tester D] Inaccurate display of strings that include forward slash

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W10-3/tp#245]
Describe the bug: 
For inputs that contain `/` , the characters behind the forward are not displayed, which might not be intentional.

How to reproduce:
`prog edit /p 1 /ad chest/back`

Expected output:
`Created new day: chest\back`

Screenshot:

![image.png](https://raw.githubusercontent.com/glenn-chew/ped/main/files/f51a0571-d4f5-4dbb-b012-605e2377f900.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: glenn-chew/ped#1

**Comment by TVageesan** [comment]
Non-issue, but need to update UG to specify that '/' is a reserved flag
