### ISSUE TITLE
[PE-D][Tester C] Volume of water cannot be higher than a certain value before being treated as infinity

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W10-3/tp#249]
![image.png](https://raw.githubusercontent.com/Paulifyer/ped/main/files/3557ed02-253b-4aef-b2ed-8884e719db2d.png)
Unsure if intended behaviour or not

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Paulifyer/ped#6

**Comment by TVageesan** [comment]
Points to a underlying issue with how we parse integers - need to check for infinity value as well
