### ISSUE TITLE
[PE-D][Tester C] Unsure if this section is implemented or a proposed feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W10-3/tp#278]
![image.png](https://raw.githubusercontent.com/Paulifyer/ped/main/files/f4f50835-149c-45f6-8ffd-1205d03f65f1.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Paulifyer/ped#12

**Comment by TVageesan** [comment]
Skill issue
