### ISSUE TITLE
[PE-D][Tester E] PDF file text not selectable

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W10-3/tp#280]
The content in `UserGuide.md` and `DeveloperGuide.md` is not selectable and not searchable through crtl+F. 
It's inconvenient for user to find what they are looking for.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: tsoudibi/ped#6

**Comment by TVageesan** [comment]
Duplicate issue: #242
